# Required fields for template
name: Bug Report
description: Please use this issue template to raise bugs
# about: Please use this issue template to raise bugs

# Optional fields for template
title: "[ENV] [FEATURE_CODE] [FEATURE_TITLE]"
labels: [bug]
assignees: []
projects: []

# Optional Body Field (Do not change the structure before discussing with Heads/Managers)
body:
- type: markdown
  attributes:
    value: |
      #### Instruction

      - Write the name of the Environment (DEV/STAGE/PRODUCTION) in the [ENV] tag in the title
      - Please fill in the below fields to raise an issue/card for a bug.
      - You can detail the bug in the description. You can use the Markdown Editor fields as you prefer.
      - Please edit the labels and assignees
- type: dropdown
  id: bug-environment
  attributes:
    label: Environment or Server
    description: Please select the server where the bug was found. Select All if this is a bug affecting all servers.
    options:
      - **Select One**
      - Dev Server 1
      - Dev Server 2
      - Staging/Pre-Prod
      - Production
      - All (affects all/most servers)
  validations:
    required: true
- type: input
  id: additional-bug-env
  attributes:
    label: Server Detail
    description: Add the link/details of the server/environment if it is not listed above, example: dev-server-4
    placeholder: Optional (You may add the Server URL here for ease)
  validations:
    required: false
- type: dropdown
  id: bug-team
  attributes:
    label: Application Scope
    description: Select where the bug is present (eg. Frontent, Backend)
    options:
      - **Select One**
      - Mobile App
      - Frontend (Web)
      - Backend
      - Unsure
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Bug Description
    description: |
      Add a detailed description of the bug. You may add any additional information, screenshots, screen recordings, or links here.
    placeholder: Type the bug detail here
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: Expected result of the correct flow
    placeholder: Describe the Expected Flow
  validations:
    required: true
- type: input
  id: story-link
  attributes:
    label: Link to Story
    description: Add the link to story/wiki where this feature is detailed
    placeholder: Optional
  validations:
    required: false
- type: input
  id: design-link
  attributes:
    label: Link to Design
    description: Add the link to Figma/other design file of the correct flow
    placeholder: Optional
  validations:
    required: false
- type: textarea
  id: repro-steps
  attributes:
    label: Steps to reproduce the bug
    description: Add concise steps to reproduce the bug. You may use the bullet-point syntax below, or use your preferred style.
    value: |
      - Example Step 1
      - Example Step 2
  validations:
    required: true
- type: checkboxes
  id: raised-by
  attributes:
    label: Reported By
    description: Who is reporting the bug?
    options:
      - label: Internal (IAT) - by PAA
      - label: Internal (IAT) - by BA/Developer
      - label: UAT - by Client
      - label: Bug Tracker (Rollbar/Sentry)
  validations:
    required: true
- type: textarea
  id: additional-notes
  attributes:
    label: Additional Screenshots/Notes
    description: (Optional) Add any additional notes/screenshots/caution messages here. You could also provide your opinion/theories on why the bug may have occurred, eg. maybe due to a recent change
