# Required fields for template
name: Feature
description: Please use this issue template for any new feature development issue, irrespective of feature size.
# about: Please use this issue template for any new feature development issue, irrespective of feature size.

# Optional fields for template
title: "[FEAT-XYZ] FEATURE TITLE HERE (Replace XYZ with your feature code)"
labels: [feature]
assignees: []
projects: []

# Optional Body Field (Do not change the structure before discussing with Heads/Managers)
body:
- type: markdown
  attributes:
    value: |
      #### Instruction

      Please fill in the below fields to raise an issue/card for a feature. 
- type: textarea
  id: test
  attributes: 
    label: Reproduction Steps
    description: "This is a test"
    value: |
      Please Add the steps to reproduce below
    render: |
      ```[tasklist]
        ### Steps to Reprocude
        - [ ] 
      ``` 
  validations:
    required: true
  
